source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

#ruby '2.4.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.12'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
# gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

gem 'diplomat',        '~> 2.0', '>= 2.0.2'
gem 'sidekiq',         '~> 5.1', '>= 5.1.3'
gem 'sidekiq-cron',    '~> 0.6.3', '>= 0.6.3'
gem 'rufus-scheduler', '3.4.2' # sidekiq-cron dependency. https://github.com/ondrejbartas/sidekiq-cron/issues/199
gem 'faraday',         '~> 0.15.1'
gem 'will_paginate',   '~> 3.1', '>= 3.1.6'
gem 'searchlight',     '~> 4.1'

gem 'grape'
gem 'grape-jbuilder'
gem 'hashie'

gem 'de_notifier', git: 'http://x-oauth-basic:zyg4s-isuEFkip2xTU74@git.digitalenergy.online/de-portal/gem-de_notifier.git', ref: "201c2322e8ff2f1948002e754b947edd44ceab73"
gem 'de_activity_logger', git: 'http://x-oauth-basic:zyg4s-isuEFkip2xTU74@git.digitalenergy.online/de-portal/gem-de_activity_logger.git', ref: '52395e70c44d6298a4311784ea94ab0da620b9be'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.7', '>= 3.7.2'
  gem 'faker',              '~> 1.8.4'
  gem 'factory_bot_rails', '~> 4.8', '>= 4.8.2'
  gem 'database_cleaner',   '~> 1.6', '>= 1.6.2'
end

group :development do
  gem 'rubocop', '~> 0.55.0', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :production do
  gem 'sentry-raven'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
