default: &default
  resources:
    address: 192.168.0.101
    port: 3000
  usage:
    address: 192.168.0.102
    port: 3000
  products:
    address: 192.168.0.103
    port: 3000
  billing:
    address: 192.168.0.104
    port: 3000
  users:
    address: 192.168.0.105
    port: 3000
  accounting:
    address: 192.168.0.106
    port: 3000
  notifications:
    address: 192.168.0.107
    port: 3000
  pay:
    address: 192.168.0.108
    port: 3000

development:
  <<: *default

test:
  <<: *default
