development:
  payu:
    merchant: demo2
    secret: demosecret_old
  robokassa:
    robokassa_pass1: pass1
    robokassa_pass2: pass2

test:
  payu:
    merchant: demo2
    secret: demosecret_old
  robokassa:
    robokassa_pass1: pass1
    robokassa_pass2: pass2
